name: Pre-commit checks

on:
  push:
    branches:
      - main

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run pre-commit checks
        run: npm run pre-commit-check
